language: java
jdk:
- oraclejdk8
env:
  matrix:
  - PROFILE=non-existent
  - PROFILE=spring5-next
cache:
  directories:
  - $HOME/.m2
os:
- linux
branches:
  except:
  - gh-pages
sudo: false
notifications:
  slack:
    secure: R8MhMPd+FsUZonvk8D9S6QC9Qj/iXn6CptAW9Smfn6pjLVm5QeLsg2eLyY4wQDNZsku8mCG4YmJ9PuyBFaiRswqhlrMhQ+/e+79E5FHuOL/tTPV01/slOgunZmnCigLSNN0tHYNNSPTgpdxwjnjpmRhppu3ehp+VQloG+NZp1Irmp3yn06gXPMIrT31urqRvCxrF5zkY/1zAMjZX0pCvZMPzpmpZM3JHVxbxmaLfiOhJWPo4rFYd/eqPg89JCpPxH0Oca80UnXSMC5SBeRvledCqyUwMqsuADTD822Xnh9SD1Vc8QRcud+c8OW99U6+XMIJQRFESNtR8WckLNVwJc7kz3f25Lz0HURemK/z/sdryXPxoym0+YM+D3jZ31tHT6tRFed2VNFkTKeuH3IA8NccxMYqdwt2QTFQTQwEmWo7HKihbLaEWd4K3AHt8kTVukwSrQE4Mg2jf4rBsIu1PDXCq8tv7FPviwmN/CbKVda1FIlAIfi9a7yu2ONjEEDhBsix+i7YbbLdBR9qONwgBwJJCLlIRJZ5TQBwMzhhtTfsjqJ00UBDOLFKQ864qKvcpDjOoMOSg9L7nqGAtstNeAA3HMyoOAC4EGvfvsBprhY/HhQmdfP7uzCha600dylDtpqJxzseJ/rHqxBMP23RrnU2hx5RrXMAi/3RAEniJu3M=
